# Generated by Django 5.0.2 on 2024-03-02 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_alter_category_name_alter_subcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='endpoints.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image_url',
            field=models.CharField(default='/no-url', max_length=500),
        ),
    ]
