# Generated by Django 5.0.2 on 2024-03-02 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_alter_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.CharField(default='/no-url', max_length=500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='endpoints.category'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='image_url',
            field=models.CharField(default='/no-url', max_length=500),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='sub_category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='endpoints.subcategory'),
        ),
    ]
