# Generated by Django 5.0.2 on 2024-03-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_alter_category_image_url_alter_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubcategory',
            name='document_url',
            field=models.CharField(default='/no-doc-url', max_length=500),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='image_url',
            field=models.CharField(default='/no-image-url', max_length=500),
        ),
    ]
